### ISSUE TITLE
Can not connect to InfluxDB if user is not admin

### ISSUE THREAD

**Issue by cm0x4D** [cloudio-project/cloudio-cloud-backend-mongo-influx#6]
This is related to the fact that the backend checks if it's database is present at startup (Using SHOW DATABASES). This check and the potential creation of the database (which is convenient in Dev-Setups) causes the system to fail to start up if the InfluxDB user used by the backend is not admin.

We can either add an option to opt-in this behaviour or handing the exception during existence check and going on of the database is present.

**Comment by RandomReaper** [comment]
Suggestion:

1. Open the database, this should succeed in a production environment.
2. If it has failed, try to create it. This will succeed in a dev-setup.
